# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a518b118e752c5fac19c93acd72d0ba539614d2f70c6ab544b13ea0534d75c69f9e2c22d72b348527f59e5fa382f4d4e4af800790b69bd55f934d2cecfaab85

test:
  secret_key_base: 3b466bdd343ee8def9f9ff55ea1282e1001e543b7c9e953edb28aee675b64f5f30d91e9c93a5ae94eee21df26f468738c9fc7b873603ea4500efcab13ff026d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
